# Generated by Django 4.2.11 on 2024-04-24 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pfaBackend_app", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="NetworkConfiguration",),
    ]
